### ISSUE TITLE
Distribute on RetroArch's Content Downloader?

### ISSUE THREAD

**Issue by RobLoach** [TricksterGuy/bottomless-block-barrage#16]
We've been considering homebrew that we could publish on RetroArch's content downloader. Bottomless  Block Barrage would be downloadable directly through either [RetroArch](http://retroarch.com/)/[Lakka](http://www.lakka.tv/).

Would you mind if we added it so people could easily download and play this awesome game???? https://github.com/libretro/libretro-super/issues/474

**Comment by anyputer** [comment]
this 3DS homebrew looks cool! yes! It would also help share the game as I haven't heard of this before :o

**Comment by TricksterGuy** [comment]
Nice! Sorry for the delay! I'm OK with this, but a few quick questions.

Would anything need to be done on my end?
Would this automatically point to the latest release when I publish a new version?

And yeah thanks for poking this I should get back to work on it.

**Comment by RobLoach** [comment]
> Would anything need to be done on my end?

Nothing is needed on your end, just the :+1:  ... We'll use the latest releases.

> Would this automatically point to the latest release when I publish a new version?

We'll update it manually on our end, until we make a script to update it for us. No need to change workflows on your end.

Thanks so much! Hopefully it gets the project a bit more attention, and get some more movement happening.

**Comment by RobLoach** [comment]
Added! Thanks so much for the :+1:
